
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SkillTracker.Entities
{

    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Associate
    {

        public Associate()
        {

            this.Associate_Skills = new HashSet<Associate_Skills>();

        }

        [DataMember]
        public int Associate_Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Mobile { get; set; }
        [DataMember]
        public string Pic { get; set; }
        [DataMember]
        public string Gender { get; set; }
        [DataMember]
        public bool Status_Green { get; set; }
        [DataMember]
        public bool Status_Blue { get; set; }
        [DataMember]
        public bool Status_Red { get; set; }
        [DataMember]
        public bool Level_1 { get; set; }
        [DataMember]
        public bool Level_2 { get; set; }
        [DataMember]
        public bool Level_3 { get; set; }
        [DataMember]
        public string Remark { get; set; }
        [DataMember]
        public string Strength { get; set; }
        [DataMember]
        public string Weakness { get; set; }
        [DataMember]
        public string Other { get; set; }

        [DataMember]
        public virtual  ICollection<Associate_Skills> Associate_Skills { get; set; }

    }

}
