
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SkillTracker.Entities
{

    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Associate_Skills
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int Associate_Id { get; set; }
        [DataMember]
        public int Skill_Id { get; set; }
        [DataMember]
        public Nullable<int> Rating { get; set; }

        public virtual  Associate Associate { get; set; }

        [DataMember]
        public virtual  Skill Skill { get; set; }

    }

}
